version: "3.8"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'  # Prometheus UI
    volumes:
      - ./prometheus:/etc/prometheus  # Mount custom configuration
      - prom_data:/prometheus  # Persist Prometheus data
    restart: unless-stopped
    depends_on:
      - node_exporter  # Ensure node_exporter is up first

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    ports:
      - '9100:9100'  # Node exporter metrics endpoint
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'  # Expose host file system to node_exporter

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3000:3000'  # Grafana UI
    volumes:
      - grafana-storage:/var/lib/grafana  # Persist Grafana data
    restart: unless-stopped
    depends_on:
      - prometheus  # Ensure Prometheus is up first
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Set Grafana admin password

volumes:
  prom_data: {}  # Volume to persist Prometheus data
  grafana-storage: {}  # Volume to persist Grafana data
